import type { Metadata } from "next";
import "./globals.css";
import { Orbitron } from 'next/font/google'
import Whatsapp from "./componentes/whatsapp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-orbitron',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={orbitron.className}>
        {children}
        <Whatsapp />
      </body>
    </html>
  );
}
